version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - nargo
    volumes:
      - dev-db:/var/lib/postgresql/data

  test-db:
    image: postgres
    ports:
      - 5435:5432
    env_file:
      - .env.test
    networks:
      - nargo

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env
    networks:
      - nargo
    volumes:
      - cache:/data

networks:
  nargo:

volumes:
  cache:
    driver: local
  dev-db:
    driver: local
