version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - dev-db
      - cache
    networks:
      - nargo

  dev-db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nargo
    volumes:
      - dev-db:/var/lib/postgresql/data

  # test-db:
  #   image: postgres:15-alpine
  #   ports:
  #     - 5435:5432
  #   env_file:
  #     - .env.test
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   networks:
  #     - nargo

  cache:
    container_name: cache
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env
    networks:
      - nargo
    volumes:
      - cache:/data

networks:
  nargo:
    driver: bridge

volumes:
  cache:
    driver: local
  dev-db:
    driver: local
